services:
  - type: web
    name: lg-webos-smart-control
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TV_IP
        value: 192.168.50.84
      - key: TV_MAC
        value: 90:7A:BE:96:CD:E0
      - key: TV_CLIENT_KEY
        value: ""
      - key: PORT
        value: 10000
