services:
  - type: web
    name: lg-webos-smart-control
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TV_IP
        value: 192.168.50.145
      - key: TV_MAC
        value: DC:03:98:69:CC:9A
      - key: TV_CLIENT_KEY
        value: 7d5d8bb32bcaffe8539149791e4cb037
      - key: PORT
        value: 10000
